REDDIT_SUBREDDITS = ["soccer", "championsleague", "football", "seriea", "PremierLeague", "LaLiga", "Bundesliga", "Ligue1"]

tgt_lang = "en"
BATCH_SIZE = 100
REDDIT_COMMENT_CLEANING_LABELS = ['Bot','Human-Conversation']
REDDIT_COMMENT_CLEANING_LABELS_STR = ",".join(REDDIT_COMMENT_CLEANING_LABELS)

MODEL_COMMENT_CLEANING = "qwen2.5:7b"

PROMPT_COMMENT_CLEANING_SUBMISSION = (
    "You are a Reddit subreddit moderator tasked with categorizing comments into one of the following labels: 'Bot' or 'Human-Conversation'. "
    "For each comment, you will also be provided with the title of the original submission to help you understand the context. "
    "Output format: label.\n"
    "Important note: Your output must be one single word, and you must output exactly one of these labels. "
    "Do not include explanations, notes, or anything other than the label itself.\n"
    "Labels: ['Bot', 'Human-Conversation'].\n\n"
    
    "Definitions:\n"
    "1. **Bot**: A comment that meets any of the following criteria:\n"
    "   - Explicitly states that it is generated by a bot or that it performs automated actions.\n"
    "   - Follows common bot patterns such as:\n"
    "     - Reminders about Reddit rules or etiquette.\n"
    "     - Invitations to join community links like Discord.\n"
    "     - Directions to contact moderators or message links.\n"
    "     - Content typically found in 'Match Thread' or 'Discussion Thread' comments.\n\n"
    "2. **Human-Conversation**: A comment that:\n"
    "   - Reflects personal thoughts, opinions, or casual conversation.\n"
    "   - Does not exhibit automated patterns or mention being a bot.\n\n"
    
    "Output format: **one label**.\n\n"
    
    "Examples:\n"
    '1. Submission title: "Premier League Discussion". Comment: "I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/PremierLeague) if you have any questions or concerns." -> "Bot".\n'
    '2. Submission title: "Company doing well in the League". Comment: "After the game, you can now legitimately say that Company is doing a really good job so far." -> "Human-Conversation".\n'
    '3. Submission title: "Football discussion". Comment: "Go watch your local club first." -> "Human-Conversation".\n'
    '4. Submission title: "Question about football". Comment: "I don’t put too mind into what those guys in the studio always say." -> "Human-Conversation".\n'
    '5. Submission title: "Looking for tips". Comment: "Wiki shows it kind of similair." -> "Human-Conversation".\n'
    '6. Submission title: "New jersey inquiry". Comment: "You can get it customised by going on their official website. It is pretty easy there." -> "Human-Conversation".\n'
    
    "Crucial reminder: Only classify a comment as 'Bot' if it explicitly states that it is a bot or shows clear automated behavior. "
    "If it expresses any human sentiment or perspective, it should be classified as 'Human-Conversation'."
    "\n\nThe comment text and submission title to categorize are provided inside ```.\n\n"
)


# Supabase table details
REDDIT_EMBEDDINGS_TABLE = "reddit_embeddings"
REDDIT_SUBMISSIONS_TABLE = "reddit_submissions"
REDDIT_SUMMARY_TABLE = "reddit_summary"

